export const validPlayers = {
  "cade": true,
  "naomi": true,
  "ator": true,
  "storn": true,
  "olorin": true,
  "crainer": true,
  "ikoll": true,
  "mar": true,
  "indominous": true,
  "phira": true,
  "shade": true,
  "osbellum": true,
  "osmetallum": true,
  "luvrunint"; true
}

export const playerVariations = {
  "cade goodbarrel": "cade",
  "cadegoodbarrel": "cade",
  "ator htailog": "ator",
  "atorhtailog": "ator",
  "crainer caracas": "crainer",
  "crainercaracas": "crainer",
  "jondo": "crainer",
  "maurice": "crainer",
  "lucy": "crainer",
  "tania": "crainer",
  "jondocaracas": "crainer",
  "jondo caracas": "crainer",
  "mauricecaracas": "crainer",
  "maurice caracas": "crainer",
  "lucycaracas": "crainer",
  "lucy caracas": "crainer",
  "taniacaracas": "crainer",
  "tania caracas": "crainer",
  "naomi samara": "naomi",
  "naomisamara": "naomi",
  "indominous von zarovich": "indominous",
  "indominous vonzarovich": "indominous",
  "indominousvonzarovich": "indominous",
  "indominousvon zarovich": "indominous",
  "nameless": "indominous",
  "shade goodbarrel": "shade",
  "shadegoodbarrel": "shade",
  "phira": "phira weneh",
  "phira": "phira squatamus",
  "phira": "phiraweneh",
  "phira": "phirasquatamus",
  "mar corvus": "mar",
  "marcorvus": "mar",
  "olorin corvus": "olorin",
  "olorincorvus": "olorin",
  "stron helderian": "storn",
  "stronhelderian": "storn",
}
